import * as ExcelJS from "exceljs";
import {
  AttendanceReportRow,
  LeaveReportRow,
  TaskReportRow,
  ReimbursementReportRow,
  ProjectReportRow
} from "./reportService";

const styleHeaderRow = (headerRow: ExcelJS.Row) => {
  headerRow.font = { name: "Arial", size: 10, bold: true, color: { argb: "FFFFFF" } };
  headerRow.eachCell((cell) => {
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "1E293B" },
    };
    cell.alignment = { vertical: "middle", horizontal: "left" };
  });
};

const setupSheetMeta = (
  worksheet: ExcelJS.Worksheet,
  title: string,
  orgName: string,
  dateRange: string,
  generatedBy: string,
  mergeRange: string
) => {
  worksheet.mergeCells(mergeRange);
  const titleCell = worksheet.getCell("A1");
  titleCell.value = title;
  titleCell.font = { name: "Arial", size: 16, bold: true, color: { argb: "0284C7" } };

  worksheet.getCell("A2").value = `Organization: ${orgName}`;
  worksheet.getCell("A2").font = { name: "Arial", size: 10, italic: true };

  worksheet.getCell("A3").value = `Date Range: ${dateRange}`;
  worksheet.getCell("A3").font = { name: "Arial", size: 10 };

  worksheet.getCell("A4").value = `Generated By: ${generatedBy} | Date: ${new Date().toLocaleDateString()}`;
  worksheet.getCell("A4").font = { name: "Arial", size: 10 };
};

export async function generateAttendanceExcel(
  rows: AttendanceReportRow[],
  orgName: string,
  dateRange: string,
  generatedBy: string
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet("Attendance");

  setupSheetMeta(worksheet, "Attendance Report", orgName, dateRange, generatedBy, "A1:I1");

  worksheet.columns = [
    { header: "Date", key: "date", width: 15 },
    { header: "Emp ID", key: "employeeId", width: 15 },
    { header: "Employee Name", key: "employeeName", width: 25 },
    { header: "Department", key: "department", width: 20 },
    { header: "Check-In", key: "checkIn", width: 15 },
    { header: "Check-Out", key: "checkOut", width: 15 },
    { header: "Hours Worked", key: "hoursWorked", width: 15 },
    { header: "Latitude", key: "latitude", width: 15 },
    { header: "Longitude", key: "longitude", width: 15 }
  ];

  const headerRow = worksheet.getRow(6);
  headerRow.values = ["Date", "Emp ID", "Employee Name", "Department", "Check-In", "Check-Out", "Hours Worked", "Latitude", "Longitude"];
  styleHeaderRow(headerRow);

  rows.forEach((row) => {
    worksheet.addRow(row);
  });

  const buffer = await workbook.xlsx.writeBuffer() as unknown as Buffer;
  return buffer;
}

export async function generateLeaveExcel(
  rows: LeaveReportRow[],
  orgName: string,
  dateRange: string,
  generatedBy: string
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet("Leaves");

  setupSheetMeta(worksheet, "Leave Request Report", orgName, dateRange, generatedBy, "A1:I1");

  worksheet.columns = [
    { header: "Start Date", key: "startDate", width: 15 },
    { header: "End Date", key: "endDate", width: 15 },
    { header: "Emp ID", key: "employeeId", width: 15 },
    { header: "Employee Name", key: "employeeName", width: 25 },
    { header: "Type", key: "type", width: 15 },
    { header: "Days", key: "dayCount", width: 10 },
    { header: "Status", key: "status", width: 15 },
    { header: "Reason", key: "reason", width: 35 },
    { header: "Reviewed By", key: "reviewedBy", width: 20 }
  ];

  const headerRow = worksheet.getRow(6);
  headerRow.values = ["Start Date", "End Date", "Emp ID", "Employee Name", "Type", "Days", "Status", "Reason", "Reviewed By"];
  styleHeaderRow(headerRow);

  rows.forEach((row) => {
    worksheet.addRow(row);
  });

  const buffer = await workbook.xlsx.writeBuffer() as unknown as Buffer;
  return buffer;
}

export async function generateTaskExcel(
  rows: TaskReportRow[],
  orgName: string,
  dateRange: string,
  generatedBy: string
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet("Tasks");

  setupSheetMeta(worksheet, "Task/Productivity Report", orgName, dateRange, generatedBy, "A1:H1");

  worksheet.columns = [
    { header: "Date", key: "date", width: 15 },
    { header: "Emp ID", key: "employeeId", width: 15 },
    { header: "Employee Name", key: "employeeName", width: 25 },
    { header: "Task Title", key: "taskTitle", width: 40 },
    { header: "Project", key: "projectName", width: 25 },
    { header: "Status", key: "status", width: 15 },
    { header: "Assigned By", key: "assignedBy", width: 20 },
    { header: "Completed At", key: "completedAt", width: 25 }
  ];

  const headerRow = worksheet.getRow(6);
  headerRow.values = ["Date", "Emp ID", "Employee Name", "Task Title", "Project", "Status", "Assigned By", "Completed At"];
  styleHeaderRow(headerRow);

  rows.forEach((row) => {
    worksheet.addRow(row);
  });

  const buffer = await workbook.xlsx.writeBuffer() as unknown as Buffer;
  return buffer;
}

export async function generateReimbursementExcel(
  rows: ReimbursementReportRow[],
  orgName: string,
  dateRange: string,
  generatedBy: string
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet("Reimbursements");

  setupSheetMeta(worksheet, "Reimbursement Report", orgName, dateRange, generatedBy, "A1:G1");

  worksheet.columns = [
    { header: "Submitted Date", key: "submittedDate", width: 15 },
    { header: "Ref Number", key: "refNumber", width: 20 },
    { header: "Emp ID", key: "employeeId", width: 15 },
    { header: "Employee Name", key: "employeeName", width: 25 },
    { header: "Title", key: "title", width: 35 },
    { header: "Status", key: "status", width: 15 },
    { header: "Amount", key: "totalAmount", width: 15 }
  ];

  const headerRow = worksheet.getRow(6);
  headerRow.values = ["Submitted Date", "Ref Number", "Emp ID", "Employee Name", "Title", "Status", "Amount"];
  styleHeaderRow(headerRow);

  rows.forEach((row) => {
    worksheet.addRow(row);
  });

  const buffer = await workbook.xlsx.writeBuffer() as unknown as Buffer;
  return buffer;
}

export async function generateProjectExcel(
  rows: ProjectReportRow[],
  orgName: string,
  dateRange: string,
  generatedBy: string
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet("Project Tasks");

  setupSheetMeta(worksheet, "Project Report", orgName, dateRange, generatedBy, "A1:F1");

  worksheet.columns = [
    { header: "Project Name", key: "projectName", width: 25 },
    { header: "Task Title", key: "taskTitle", width: 40 },
    { header: "Assignee", key: "assignee", width: 25 },
    { header: "Status", key: "status", width: 15 },
    { header: "Assigned Date", key: "assignedDate", width: 15 },
    { header: "Completed At", key: "completedAt", width: 25 }
  ];

  const headerRow = worksheet.getRow(6);
  headerRow.values = ["Project Name", "Task Title", "Assignee", "Status", "Assigned Date", "Completed At"];
  styleHeaderRow(headerRow);

  rows.forEach((row) => {
    worksheet.addRow(row);
  });

  const buffer = await workbook.xlsx.writeBuffer() as unknown as Buffer;
  return buffer;
}
