import PDFDocument from "pdfkit";
import {
  AttendanceReportRow,
  LeaveReportRow,
  TaskReportRow,
  ReimbursementReportRow,
  ProjectReportRow
} from "./reportService";

interface ColumnConfig {
  header: string;
  key: string;
  width: number;
  align?: 'left' | 'center' | 'right';
}

const drawTable = (
  doc: any,
  columns: ColumnConfig[],
  rows: any[],
  startY: number
) => {
  const margin = 50;
  const pageHeight = doc.page.height;
  const rowHeight = 22;
  let currentY = startY;

  // Header Draw helper
  const drawHeaders = (y: number) => {
    doc.fontSize(8.5).font("Helvetica-Bold").fillColor("#1E293B");
    let currentX = margin;
    for (const col of columns) {
      doc.text(col.header, currentX, y, { width: col.width, align: col.align || 'left' });
      currentX += col.width;
    }
    // Draw thick border line under headers
    doc.strokeColor("#94A3B8").lineWidth(1).moveTo(margin, y + 14).lineTo(doc.page.width - margin, y + 14).stroke();
  };

  drawHeaders(currentY);
  currentY += rowHeight;

  // Rows
  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];

    // Check page boundaries
    if (currentY + rowHeight > pageHeight - margin) {
      doc.addPage();
      currentY = margin;
      drawHeaders(currentY);
      currentY += rowHeight;
    }

    // Zebra striping background
    if (i % 2 === 1) {
      doc.save();
      doc.fillColor("#F8FAFC")
         .rect(margin, currentY - 4, doc.page.width - 2 * margin, rowHeight)
         .fill();
      doc.restore();
    }

    doc.fontSize(8).font("Helvetica").fillColor("#475569");
    let currentX = margin;
    for (const col of columns) {
      const val = row[col.key] !== undefined && row[col.key] !== null ? String(row[col.key]) : 'N/A';
      doc.text(val, currentX, currentY, { width: col.width, align: col.align || 'left', ellipsis: true });
      currentX += col.width;
    }

    // Bottom border for the row
    doc.strokeColor("#E2E8F0").lineWidth(0.5).moveTo(margin, currentY + 14).lineTo(doc.page.width - margin, currentY + 14).stroke();

    currentY += rowHeight;
  }
};

const drawHeaderBlock = (
  doc: any,
  title: string,
  orgName: string,
  dateRange: string,
  generatedBy: string
) => {
  // Title
  doc.fillColor("#0284C7").fontSize(18).font("Helvetica-Bold").text(title, { align: "left" });
  doc.moveDown(0.2);

  // Metadata block
  doc.fontSize(9).font("Helvetica").fillColor("#475569");
  doc.text(`Organization: ${orgName}`);
  doc.text(`Date Range: ${dateRange}`);
  doc.text(`Generated By: ${generatedBy} | Date: ${new Date().toLocaleDateString()}`);
  doc.moveDown(0.8);

  // Divider Line
  doc.strokeColor("#E2E8F0").lineWidth(1).moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).stroke();
  doc.moveDown(0.8);
};

export async function generateAttendancePdf(
  rows: AttendanceReportRow[],
  orgName: string,
  dateRange: string,
  generatedBy: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: "A4", layout: "landscape" });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", (err) => reject(err));

      drawHeaderBlock(doc, "Attendance Report", orgName, dateRange, generatedBy);

      // Printable width = 841.89 - 100 = 741.89 points
      // Total column widths: 80 + 75 + 110 + 90 + 65 + 65 + 75 + 90 + 90 = 740
      const columns: ColumnConfig[] = [
        { header: "Date", key: "date", width: 80 },
        { header: "Emp ID", key: "employeeId", width: 75 },
        { header: "Name", key: "employeeName", width: 110 },
        { header: "Department", key: "department", width: 90 },
        { header: "Check-In", key: "checkIn", width: 65 },
        { header: "Check-Out", key: "checkOut", width: 65 },
        { header: "Hours", key: "hoursWorked", width: 75 },
        { header: "Latitude", key: "latitude", width: 90 },
        { header: "Longitude", key: "longitude", width: 90 }
      ];

      drawTable(doc, columns, rows, doc.y);

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

export async function generateLeavePdf(
  rows: LeaveReportRow[],
  orgName: string,
  dateRange: string,
  generatedBy: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: "A4", layout: "landscape" });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", (err) => reject(err));

      drawHeaderBlock(doc, "Leave Request Report", orgName, dateRange, generatedBy);

      // Total width: 70 + 70 + 75 + 100 + 70 + 50 + 70 + 135 + 100 = 740
      const columns: ColumnConfig[] = [
        { header: "Start Date", key: "startDate", width: 70 },
        { header: "End Date", key: "endDate", width: 70 },
        { header: "Emp ID", key: "employeeId", width: 75 },
        { header: "Name", key: "employeeName", width: 100 },
        { header: "Type", key: "type", width: 70 },
        { header: "Days", key: "dayCount", width: 50, align: "center" },
        { header: "Status", key: "status", width: 70 },
        { header: "Reason", key: "reason", width: 135 },
        { header: "Reviewed By", key: "reviewedBy", width: 100 }
      ];

      drawTable(doc, columns, rows, doc.y);

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

export async function generateTaskPdf(
  rows: TaskReportRow[],
  orgName: string,
  dateRange: string,
  generatedBy: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: "A4", layout: "landscape" });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", (err) => reject(err));

      drawHeaderBlock(doc, "Task/Productivity Report", orgName, dateRange, generatedBy);

      // Total width: 80 + 75 + 110 + 180 + 100 + 75 + 60 + 60 = 740
      const columns: ColumnConfig[] = [
        { header: "Date", key: "date", width: 80 },
        { header: "Emp ID", key: "employeeId", width: 75 },
        { header: "Employee Name", key: "employeeName", width: 110 },
        { header: "Task Title", key: "taskTitle", width: 180 },
        { header: "Project", key: "projectName", width: 100 },
        { header: "Status", key: "status", width: 75 },
        { header: "Assigned By", key: "assignedBy", width: 60 },
        { header: "Completed At", key: "completedAt", width: 60 }
      ];

      drawTable(doc, columns, rows, doc.y);

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

export async function generateReimbursementPdf(
  rows: ReimbursementReportRow[],
  orgName: string,
  dateRange: string,
  generatedBy: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: "A4", layout: "landscape" });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", (err) => reject(err));

      drawHeaderBlock(doc, "Reimbursement Report", orgName, dateRange, generatedBy);

      // Total width: 90 + 110 + 80 + 120 + 180 + 80 + 80 = 740
      const columns: ColumnConfig[] = [
        { header: "Submitted Date", key: "submittedDate", width: 90 },
        { header: "Ref Number", key: "refNumber", width: 110 },
        { header: "Emp ID", key: "employeeId", width: 80 },
        { header: "Employee Name", key: "employeeName", width: 120 },
        { header: "Title", key: "title", width: 180 },
        { header: "Status", key: "status", width: 80 },
        { header: "Amount", key: "totalAmount", width: 80, align: "right" }
      ];

      drawTable(doc, columns, rows, doc.y);

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

export async function generateProjectPdf(
  rows: ProjectReportRow[],
  orgName: string,
  dateRange: string,
  generatedBy: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: "A4", layout: "landscape" });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", (err) => reject(err));

      drawHeaderBlock(doc, "Project Report", orgName, dateRange, generatedBy);

      // Total width: 120 + 200 + 120 + 80 + 110 + 110 = 740
      const columns: ColumnConfig[] = [
        { header: "Project Name", key: "projectName", width: 120 },
        { header: "Task Title", key: "taskTitle", width: 200 },
        { header: "Assignee", key: "assignee", width: 120 },
        { header: "Status", key: "status", width: 80 },
        { header: "Assigned Date", key: "assignedDate", width: 110 },
        { header: "Completed At", key: "completedAt", width: 110 }
      ];

      drawTable(doc, columns, rows, doc.y);

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
